name: Build and Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli
    - name: NPM install
      run: npm install
    - name: Gatsby build
      run: gatsby build
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.SecretId }}
        SECRET_KEY: ${{ secrets.SecretKey }}
        BUCKET: ${{ secrets.Bucket }}
        REGION: ${{ secrets.Region }}
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Upload to cos
      run: coscmd upload -rs ./public/ /
    - name: refresh CDN
      uses: keithnull/tencent-cloud-cdn-purge-cache@v1.0
      env:
        SECRET_ID: ${{ secrets.SecretId }}
        SECRET_KEY: ${{ secrets.SecretKey }}
        PATHS: "https://beta.imwzk.com/"
