name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli
      - name: NPM install
        run: npm install
      - name: Gatsby build
        run: gatsby build
